//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18033.
// 
#pragma warning disable 1591

namespace AgileMind.Website.GamesWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GamesServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RelatedEnd))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StructuralObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityKeyMember[]))]
    public partial class GamesService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback FetchColorGameOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertGameResultOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertGameResultWebOperationCompleted;
        
        private System.Threading.SendOrPostCallback FetchUserProfileQuestionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback HasUserFilledOutQuestionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveUserProfileQuestionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback FetchRandomQuizQuestionsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GamesService() {
            this.Url = global::AgileMind.Website.Properties.Settings.Default.AgileMind_Website_GamesWS_GamesService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event FetchColorGameCompletedEventHandler FetchColorGameCompleted;
        
        /// <remarks/>
        public event InsertGameResultCompletedEventHandler InsertGameResultCompleted;
        
        /// <remarks/>
        public event InsertGameResultWebCompletedEventHandler InsertGameResultWebCompleted;
        
        /// <remarks/>
        public event FetchUserProfileQuestionsCompletedEventHandler FetchUserProfileQuestionsCompleted;
        
        /// <remarks/>
        public event HasUserFilledOutQuestionsCompletedEventHandler HasUserFilledOutQuestionsCompleted;
        
        /// <remarks/>
        public event SaveUserProfileQuestionsCompletedEventHandler SaveUserProfileQuestionsCompleted;
        
        /// <remarks/>
        public event FetchRandomQuizQuestionsCompletedEventHandler FetchRandomQuizQuestionsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FetchColorGame", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ColorGameResult FetchColorGame() {
            object[] results = this.Invoke("FetchColorGame", new object[0]);
            return ((ColorGameResult)(results[0]));
        }
        
        /// <remarks/>
        public void FetchColorGameAsync() {
            this.FetchColorGameAsync(null);
        }
        
        /// <remarks/>
        public void FetchColorGameAsync(object userState) {
            if ((this.FetchColorGameOperationCompleted == null)) {
                this.FetchColorGameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFetchColorGameOperationCompleted);
            }
            this.InvokeAsync("FetchColorGame", new object[0], this.FetchColorGameOperationCompleted, userState);
        }
        
        private void OnFetchColorGameOperationCompleted(object arg) {
            if ((this.FetchColorGameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FetchColorGameCompleted(this, new FetchColorGameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertGameResult", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GameResults InsertGameResult(string UserName, string Password, GameListEnum gameType, int Score, decimal TestDuration, int Total) {
            object[] results = this.Invoke("InsertGameResult", new object[] {
                        UserName,
                        Password,
                        gameType,
                        Score,
                        TestDuration,
                        Total});
            return ((GameResults)(results[0]));
        }
        
        /// <remarks/>
        public void InsertGameResultAsync(string UserName, string Password, GameListEnum gameType, int Score, decimal TestDuration, int Total) {
            this.InsertGameResultAsync(UserName, Password, gameType, Score, TestDuration, Total, null);
        }
        
        /// <remarks/>
        public void InsertGameResultAsync(string UserName, string Password, GameListEnum gameType, int Score, decimal TestDuration, int Total, object userState) {
            if ((this.InsertGameResultOperationCompleted == null)) {
                this.InsertGameResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertGameResultOperationCompleted);
            }
            this.InvokeAsync("InsertGameResult", new object[] {
                        UserName,
                        Password,
                        gameType,
                        Score,
                        TestDuration,
                        Total}, this.InsertGameResultOperationCompleted, userState);
        }
        
        private void OnInsertGameResultOperationCompleted(object arg) {
            if ((this.InsertGameResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertGameResultCompleted(this, new InsertGameResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertGameResultWeb", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GameResults InsertGameResultWeb(string UserName, GameListEnum gameType, int Score, decimal TestDuration, int Total) {
            object[] results = this.Invoke("InsertGameResultWeb", new object[] {
                        UserName,
                        gameType,
                        Score,
                        TestDuration,
                        Total});
            return ((GameResults)(results[0]));
        }
        
        /// <remarks/>
        public void InsertGameResultWebAsync(string UserName, GameListEnum gameType, int Score, decimal TestDuration, int Total) {
            this.InsertGameResultWebAsync(UserName, gameType, Score, TestDuration, Total, null);
        }
        
        /// <remarks/>
        public void InsertGameResultWebAsync(string UserName, GameListEnum gameType, int Score, decimal TestDuration, int Total, object userState) {
            if ((this.InsertGameResultWebOperationCompleted == null)) {
                this.InsertGameResultWebOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertGameResultWebOperationCompleted);
            }
            this.InvokeAsync("InsertGameResultWeb", new object[] {
                        UserName,
                        gameType,
                        Score,
                        TestDuration,
                        Total}, this.InsertGameResultWebOperationCompleted, userState);
        }
        
        private void OnInsertGameResultWebOperationCompleted(object arg) {
            if ((this.InsertGameResultWebCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertGameResultWebCompleted(this, new InsertGameResultWebCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FetchUserProfileQuestions", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserProfileQuestionsResults FetchUserProfileQuestions(System.Guid SessionId) {
            object[] results = this.Invoke("FetchUserProfileQuestions", new object[] {
                        SessionId});
            return ((UserProfileQuestionsResults)(results[0]));
        }
        
        /// <remarks/>
        public void FetchUserProfileQuestionsAsync(System.Guid SessionId) {
            this.FetchUserProfileQuestionsAsync(SessionId, null);
        }
        
        /// <remarks/>
        public void FetchUserProfileQuestionsAsync(System.Guid SessionId, object userState) {
            if ((this.FetchUserProfileQuestionsOperationCompleted == null)) {
                this.FetchUserProfileQuestionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFetchUserProfileQuestionsOperationCompleted);
            }
            this.InvokeAsync("FetchUserProfileQuestions", new object[] {
                        SessionId}, this.FetchUserProfileQuestionsOperationCompleted, userState);
        }
        
        private void OnFetchUserProfileQuestionsOperationCompleted(object arg) {
            if ((this.FetchUserProfileQuestionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FetchUserProfileQuestionsCompleted(this, new FetchUserProfileQuestionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HasUserFilledOutQuestions", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool HasUserFilledOutQuestions(System.Guid SessionId) {
            object[] results = this.Invoke("HasUserFilledOutQuestions", new object[] {
                        SessionId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void HasUserFilledOutQuestionsAsync(System.Guid SessionId) {
            this.HasUserFilledOutQuestionsAsync(SessionId, null);
        }
        
        /// <remarks/>
        public void HasUserFilledOutQuestionsAsync(System.Guid SessionId, object userState) {
            if ((this.HasUserFilledOutQuestionsOperationCompleted == null)) {
                this.HasUserFilledOutQuestionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHasUserFilledOutQuestionsOperationCompleted);
            }
            this.InvokeAsync("HasUserFilledOutQuestions", new object[] {
                        SessionId}, this.HasUserFilledOutQuestionsOperationCompleted, userState);
        }
        
        private void OnHasUserFilledOutQuestionsOperationCompleted(object arg) {
            if ((this.HasUserFilledOutQuestionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HasUserFilledOutQuestionsCompleted(this, new HasUserFilledOutQuestionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveUserProfileQuestions", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result SaveUserProfileQuestions(vwQuestionAnswer[] QuestionAnswerList, System.Guid SessionId) {
            object[] results = this.Invoke("SaveUserProfileQuestions", new object[] {
                        QuestionAnswerList,
                        SessionId});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void SaveUserProfileQuestionsAsync(vwQuestionAnswer[] QuestionAnswerList, System.Guid SessionId) {
            this.SaveUserProfileQuestionsAsync(QuestionAnswerList, SessionId, null);
        }
        
        /// <remarks/>
        public void SaveUserProfileQuestionsAsync(vwQuestionAnswer[] QuestionAnswerList, System.Guid SessionId, object userState) {
            if ((this.SaveUserProfileQuestionsOperationCompleted == null)) {
                this.SaveUserProfileQuestionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveUserProfileQuestionsOperationCompleted);
            }
            this.InvokeAsync("SaveUserProfileQuestions", new object[] {
                        QuestionAnswerList,
                        SessionId}, this.SaveUserProfileQuestionsOperationCompleted, userState);
        }
        
        private void OnSaveUserProfileQuestionsOperationCompleted(object arg) {
            if ((this.SaveUserProfileQuestionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveUserProfileQuestionsCompleted(this, new SaveUserProfileQuestionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FetchRandomQuizQuestions", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProfileQuizQuestionRequest FetchRandomQuizQuestions(System.Guid SessionId, int QuestionCount) {
            object[] results = this.Invoke("FetchRandomQuizQuestions", new object[] {
                        SessionId,
                        QuestionCount});
            return ((ProfileQuizQuestionRequest)(results[0]));
        }
        
        /// <remarks/>
        public void FetchRandomQuizQuestionsAsync(System.Guid SessionId, int QuestionCount) {
            this.FetchRandomQuizQuestionsAsync(SessionId, QuestionCount, null);
        }
        
        /// <remarks/>
        public void FetchRandomQuizQuestionsAsync(System.Guid SessionId, int QuestionCount, object userState) {
            if ((this.FetchRandomQuizQuestionsOperationCompleted == null)) {
                this.FetchRandomQuizQuestionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFetchRandomQuizQuestionsOperationCompleted);
            }
            this.InvokeAsync("FetchRandomQuizQuestions", new object[] {
                        SessionId,
                        QuestionCount}, this.FetchRandomQuizQuestionsOperationCompleted, userState);
        }
        
        private void OnFetchRandomQuizQuestionsOperationCompleted(object arg) {
            if ((this.FetchRandomQuizQuestionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FetchRandomQuizQuestionsCompleted(this, new FetchRandomQuizQuestionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ColorGameResult : Result {
        
        private ColorGameQuestion[] questionsField;
        
        /// <remarks/>
        public ColorGameQuestion[] Questions {
            get {
                return this.questionsField;
            }
            set {
                this.questionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ColorGameQuestion {
        
        private string leftWordField;
        
        private string leftColorField;
        
        private string rightWordField;
        
        private string rightColorField;
        
        private bool isMatchField;
        
        private bool userCorrectField;
        
        /// <remarks/>
        public string LeftWord {
            get {
                return this.leftWordField;
            }
            set {
                this.leftWordField = value;
            }
        }
        
        /// <remarks/>
        public string LeftColor {
            get {
                return this.leftColorField;
            }
            set {
                this.leftColorField = value;
            }
        }
        
        /// <remarks/>
        public string RightWord {
            get {
                return this.rightWordField;
            }
            set {
                this.rightWordField = value;
            }
        }
        
        /// <remarks/>
        public string RightColor {
            get {
                return this.rightColorField;
            }
            set {
                this.rightColorField = value;
            }
        }
        
        /// <remarks/>
        public bool IsMatch {
            get {
                return this.isMatchField;
            }
            set {
                this.isMatchField = value;
            }
        }
        
        /// <remarks/>
        public bool UserCorrect {
            get {
                return this.userCorrectField;
            }
            set {
                this.userCorrectField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProfileQuizQuestion {
        
        private string questionField;
        
        private string answerField;
        
        private string userAnswerField;
        
        /// <remarks/>
        public string Question {
            get {
                return this.questionField;
            }
            set {
                this.questionField = value;
            }
        }
        
        /// <remarks/>
        public string Answer {
            get {
                return this.answerField;
            }
            set {
                this.answerField = value;
            }
        }
        
        /// <remarks/>
        public string UserAnswer {
            get {
                return this.userAnswerField;
            }
            set {
                this.userAnswerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOft_Game))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfLogin))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class RelatedEnd {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOft_Game))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfLogin))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class EntityReference : RelatedEnd {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityKey {
        
        private string entitySetNameField;
        
        private string entityContainerNameField;
        
        private EntityKeyMember[] entityKeyValuesField;
        
        /// <remarks/>
        public string EntitySetName {
            get {
                return this.entitySetNameField;
            }
            set {
                this.entitySetNameField = value;
            }
        }
        
        /// <remarks/>
        public string EntityContainerName {
            get {
                return this.entityContainerNameField;
            }
            set {
                this.entityContainerNameField = value;
            }
        }
        
        /// <remarks/>
        public EntityKeyMember[] EntityKeyValues {
            get {
                return this.entityKeyValuesField;
            }
            set {
                this.entityKeyValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityKeyMember {
        
        private string keyField;
        
        private object valueField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityReferenceOft_Game : EntityReference {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityReferenceOfLogin : EntityReference {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(t_GameResults))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(vwQuestionAnswer))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class StructuralObject {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(t_GameResults))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(vwQuestionAnswer))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class EntityObject : StructuralObject {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class t_GameResults : EntityObject {
        
        private int gameScoreIdField;
        
        private int gameIdField;
        
        private int loginIdField;
        
        private System.DateTime createdField;
        
        private int scoreField;
        
        private int totalField;
        
        private System.Nullable<decimal> testDurationField;
        
        private EntityReferenceOfLogin loginReferenceField;
        
        private EntityReferenceOft_Game t_GameReferenceField;
        
        /// <remarks/>
        public int GameScoreId {
            get {
                return this.gameScoreIdField;
            }
            set {
                this.gameScoreIdField = value;
            }
        }
        
        /// <remarks/>
        public int GameId {
            get {
                return this.gameIdField;
            }
            set {
                this.gameIdField = value;
            }
        }
        
        /// <remarks/>
        public int LoginId {
            get {
                return this.loginIdField;
            }
            set {
                this.loginIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        public int Score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
            }
        }
        
        /// <remarks/>
        public int Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> TestDuration {
            get {
                return this.testDurationField;
            }
            set {
                this.testDurationField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOfLogin LoginReference {
            get {
                return this.loginReferenceField;
            }
            set {
                this.loginReferenceField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOft_Game t_GameReference {
            get {
                return this.t_GameReferenceField;
            }
            set {
                this.t_GameReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class vwQuestionAnswer : EntityObject {
        
        private int userProfileQuestionIdField;
        
        private string questionField;
        
        private byte orderField;
        
        private System.DateTime createdField;
        
        private bool activeField;
        
        private System.Nullable<int> userProfileAnswerIdField;
        
        private System.Nullable<int> loginIdField;
        
        private string answerField;
        
        private System.Nullable<System.DateTime> answerCreatedField;
        
        private System.Nullable<bool> noAnswerField;
        
        /// <remarks/>
        public int UserProfileQuestionId {
            get {
                return this.userProfileQuestionIdField;
            }
            set {
                this.userProfileQuestionIdField = value;
            }
        }
        
        /// <remarks/>
        public string Question {
            get {
                return this.questionField;
            }
            set {
                this.questionField = value;
            }
        }
        
        /// <remarks/>
        public byte Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> UserProfileAnswerId {
            get {
                return this.userProfileAnswerIdField;
            }
            set {
                this.userProfileAnswerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> LoginId {
            get {
                return this.loginIdField;
            }
            set {
                this.loginIdField = value;
            }
        }
        
        /// <remarks/>
        public string Answer {
            get {
                return this.answerField;
            }
            set {
                this.answerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> AnswerCreated {
            get {
                return this.answerCreatedField;
            }
            set {
                this.answerCreatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> NoAnswer {
            get {
                return this.noAnswerField;
            }
            set {
                this.noAnswerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProfileQuizQuestionRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserProfileQuestionsResults))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GameResults))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ColorGameResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Result {
        
        private bool successField;
        
        private string errorField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProfileQuizQuestionRequest : Result {
        
        private ProfileQuizQuestion[] questionListField;
        
        /// <remarks/>
        public ProfileQuizQuestion[] QuestionList {
            get {
                return this.questionListField;
            }
            set {
                this.questionListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserProfileQuestionsResults : Result {
        
        private vwQuestionAnswer[] questionListField;
        
        /// <remarks/>
        public vwQuestionAnswer[] QuestionList {
            get {
                return this.questionListField;
            }
            set {
                this.questionListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GameResults : Result {
        
        private t_GameResults gameField;
        
        /// <remarks/>
        public t_GameResults Game {
            get {
                return this.gameField;
            }
            set {
                this.gameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum GameListEnum {
        
        /// <remarks/>
        ColorQuiz,
        
        /// <remarks/>
        UserProfileQuestions,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void FetchColorGameCompletedEventHandler(object sender, FetchColorGameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FetchColorGameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FetchColorGameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ColorGameResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ColorGameResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void InsertGameResultCompletedEventHandler(object sender, InsertGameResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertGameResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertGameResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GameResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GameResults)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void InsertGameResultWebCompletedEventHandler(object sender, InsertGameResultWebCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertGameResultWebCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertGameResultWebCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GameResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GameResults)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void FetchUserProfileQuestionsCompletedEventHandler(object sender, FetchUserProfileQuestionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FetchUserProfileQuestionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FetchUserProfileQuestionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserProfileQuestionsResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserProfileQuestionsResults)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void HasUserFilledOutQuestionsCompletedEventHandler(object sender, HasUserFilledOutQuestionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasUserFilledOutQuestionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HasUserFilledOutQuestionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SaveUserProfileQuestionsCompletedEventHandler(object sender, SaveUserProfileQuestionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveUserProfileQuestionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveUserProfileQuestionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void FetchRandomQuizQuestionsCompletedEventHandler(object sender, FetchRandomQuizQuestionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FetchRandomQuizQuestionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FetchRandomQuizQuestionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProfileQuizQuestionRequest Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProfileQuizQuestionRequest)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591