//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("AgileMindModel", "FK_t_GameResults_Logins", "Login", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AgileMind.DAL.Data.Login), "t_GameResults", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AgileMind.DAL.Data.t_GameResults), true)]
[assembly: EdmRelationshipAttribute("AgileMindModel", "FK_t_GameResults_t_Game", "t_Game", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AgileMind.DAL.Data.t_Game), "t_GameResults", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AgileMind.DAL.Data.t_GameResults), true)]
[assembly: EdmRelationshipAttribute("AgileMindModel", "FK_t_UserProfileAnswer_Logins", "Login", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AgileMind.DAL.Data.Login), "t_UserProfileAnswer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AgileMind.DAL.Data.t_UserProfileAnswer), true)]
[assembly: EdmRelationshipAttribute("AgileMindModel", "FK_t_UserProfileAnswer_t_UserProfileQuestion", "t_UserProfileQuestion", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AgileMind.DAL.Data.t_UserProfileQuestion), "t_UserProfileAnswer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AgileMind.DAL.Data.t_UserProfileAnswer), true)]
[assembly: EdmRelationshipAttribute("AgileMindModel", "FK_t_LoginSession_Logins", "Login", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AgileMind.DAL.Data.Login), "t_LoginSession", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AgileMind.DAL.Data.t_LoginSession), true)]

#endregion

namespace AgileMind.DAL.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AgileMindEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AgileMindEntities object using the connection string found in the 'AgileMindEntities' section of the application configuration file.
        /// </summary>
        public AgileMindEntities() : base("name=AgileMindEntities", "AgileMindEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AgileMindEntities object.
        /// </summary>
        public AgileMindEntities(string connectionString) : base(connectionString, "AgileMindEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AgileMindEntities object.
        /// </summary>
        public AgileMindEntities(EntityConnection connection) : base(connection, "AgileMindEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Login> Logins
        {
            get
            {
                if ((_Logins == null))
                {
                    _Logins = base.CreateObjectSet<Login>("Logins");
                }
                return _Logins;
            }
        }
        private ObjectSet<Login> _Logins;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vwLoginInfo> vwLoginInfoes
        {
            get
            {
                if ((_vwLoginInfoes == null))
                {
                    _vwLoginInfoes = base.CreateObjectSet<vwLoginInfo>("vwLoginInfoes");
                }
                return _vwLoginInfoes;
            }
        }
        private ObjectSet<vwLoginInfo> _vwLoginInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<t_Game> t_Game
        {
            get
            {
                if ((_t_Game == null))
                {
                    _t_Game = base.CreateObjectSet<t_Game>("t_Game");
                }
                return _t_Game;
            }
        }
        private ObjectSet<t_Game> _t_Game;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<t_GameResults> t_GameResults
        {
            get
            {
                if ((_t_GameResults == null))
                {
                    _t_GameResults = base.CreateObjectSet<t_GameResults>("t_GameResults");
                }
                return _t_GameResults;
            }
        }
        private ObjectSet<t_GameResults> _t_GameResults;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<t_UserProfileAnswer> t_UserProfileAnswer
        {
            get
            {
                if ((_t_UserProfileAnswer == null))
                {
                    _t_UserProfileAnswer = base.CreateObjectSet<t_UserProfileAnswer>("t_UserProfileAnswer");
                }
                return _t_UserProfileAnswer;
            }
        }
        private ObjectSet<t_UserProfileAnswer> _t_UserProfileAnswer;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<t_UserProfileQuestion> t_UserProfileQuestion
        {
            get
            {
                if ((_t_UserProfileQuestion == null))
                {
                    _t_UserProfileQuestion = base.CreateObjectSet<t_UserProfileQuestion>("t_UserProfileQuestion");
                }
                return _t_UserProfileQuestion;
            }
        }
        private ObjectSet<t_UserProfileQuestion> _t_UserProfileQuestion;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<t_LoginSession> t_LoginSession
        {
            get
            {
                if ((_t_LoginSession == null))
                {
                    _t_LoginSession = base.CreateObjectSet<t_LoginSession>("t_LoginSession");
                }
                return _t_LoginSession;
            }
        }
        private ObjectSet<t_LoginSession> _t_LoginSession;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Logins EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLogins(Login login)
        {
            base.AddObject("Logins", login);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vwLoginInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovwLoginInfoes(vwLoginInfo vwLoginInfo)
        {
            base.AddObject("vwLoginInfoes", vwLoginInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the t_Game EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTot_Game(t_Game t_Game)
        {
            base.AddObject("t_Game", t_Game);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the t_GameResults EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTot_GameResults(t_GameResults t_GameResults)
        {
            base.AddObject("t_GameResults", t_GameResults);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the t_UserProfileAnswer EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTot_UserProfileAnswer(t_UserProfileAnswer t_UserProfileAnswer)
        {
            base.AddObject("t_UserProfileAnswer", t_UserProfileAnswer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the t_UserProfileQuestion EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTot_UserProfileQuestion(t_UserProfileQuestion t_UserProfileQuestion)
        {
            base.AddObject("t_UserProfileQuestion", t_UserProfileQuestion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the t_LoginSession EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTot_LoginSession(t_LoginSession t_LoginSession)
        {
            base.AddObject("t_LoginSession", t_LoginSession);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="loginName">No Metadata Documentation available.</param>
        /// <param name="password">No Metadata Documentation available.</param>
        /// <param name="iPAddress">No Metadata Documentation available.</param>
        public ObjectResult<Login> Logins_CheckLogin(global::System.String loginName, global::System.String password, global::System.String iPAddress)
        {
            ObjectParameter loginNameParameter;
            if (loginName != null)
            {
                loginNameParameter = new ObjectParameter("LoginName", loginName);
            }
            else
            {
                loginNameParameter = new ObjectParameter("LoginName", typeof(global::System.String));
            }
    
            ObjectParameter passwordParameter;
            if (password != null)
            {
                passwordParameter = new ObjectParameter("Password", password);
            }
            else
            {
                passwordParameter = new ObjectParameter("Password", typeof(global::System.String));
            }
    
            ObjectParameter iPAddressParameter;
            if (iPAddress != null)
            {
                iPAddressParameter = new ObjectParameter("IPAddress", iPAddress);
            }
            else
            {
                iPAddressParameter = new ObjectParameter("IPAddress", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<Login>("Logins_CheckLogin", loginNameParameter, passwordParameter, iPAddressParameter);
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        /// <param name="loginName">No Metadata Documentation available.</param>
        /// <param name="password">No Metadata Documentation available.</param>
        /// <param name="iPAddress">No Metadata Documentation available.</param>
        public ObjectResult<Login> Logins_CheckLogin(global::System.String loginName, global::System.String password, global::System.String iPAddress, MergeOption mergeOption)
        {
            ObjectParameter loginNameParameter;
            if (loginName != null)
            {
                loginNameParameter = new ObjectParameter("LoginName", loginName);
            }
            else
            {
                loginNameParameter = new ObjectParameter("LoginName", typeof(global::System.String));
            }
    
            ObjectParameter passwordParameter;
            if (password != null)
            {
                passwordParameter = new ObjectParameter("Password", password);
            }
            else
            {
                passwordParameter = new ObjectParameter("Password", typeof(global::System.String));
            }
    
            ObjectParameter iPAddressParameter;
            if (iPAddress != null)
            {
                iPAddressParameter = new ObjectParameter("IPAddress", iPAddress);
            }
            else
            {
                iPAddressParameter = new ObjectParameter("IPAddress", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<Login>("Logins_CheckLogin", mergeOption, loginNameParameter, passwordParameter, iPAddressParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="loginId">No Metadata Documentation available.</param>
        public ObjectResult<vwLoginInfo> vw_LoginInfo_FetchByLoginId(Nullable<global::System.Int32> loginId)
        {
            ObjectParameter loginIdParameter;
            if (loginId.HasValue)
            {
                loginIdParameter = new ObjectParameter("LoginId", loginId);
            }
            else
            {
                loginIdParameter = new ObjectParameter("LoginId", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<vwLoginInfo>("vw_LoginInfo_FetchByLoginId", loginIdParameter);
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        /// <param name="loginId">No Metadata Documentation available.</param>
        public ObjectResult<vwLoginInfo> vw_LoginInfo_FetchByLoginId(Nullable<global::System.Int32> loginId, MergeOption mergeOption)
        {
            ObjectParameter loginIdParameter;
            if (loginId.HasValue)
            {
                loginIdParameter = new ObjectParameter("LoginId", loginId);
            }
            else
            {
                loginIdParameter = new ObjectParameter("LoginId", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<vwLoginInfo>("vw_LoginInfo_FetchByLoginId", mergeOption, loginIdParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AgileMindModel", Name="Login")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Login : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Login object.
        /// </summary>
        /// <param name="loginId">Initial value of the LoginId property.</param>
        /// <param name="loginName">Initial value of the LoginName property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="emailAddress">Initial value of the EmailAddress property.</param>
        /// <param name="active">Initial value of the Active property.</param>
        /// <param name="created">Initial value of the Created property.</param>
        public static Login CreateLogin(global::System.Int32 loginId, global::System.String loginName, global::System.String password, global::System.String emailAddress, global::System.Boolean active, global::System.DateTime created)
        {
            Login login = new Login();
            login.LoginId = loginId;
            login.LoginName = loginName;
            login.Password = password;
            login.EmailAddress = emailAddress;
            login.Active = active;
            login.Created = created;
            return login;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LoginId
        {
            get
            {
                return _LoginId;
            }
            set
            {
                if (_LoginId != value)
                {
                    OnLoginIdChanging(value);
                    ReportPropertyChanging("LoginId");
                    _LoginId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LoginId");
                    OnLoginIdChanged();
                }
            }
        }
        private global::System.Int32 _LoginId;
        partial void OnLoginIdChanging(global::System.Int32 value);
        partial void OnLoginIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LoginName
        {
            get
            {
                return _LoginName;
            }
            set
            {
                OnLoginNameChanging(value);
                ReportPropertyChanging("LoginName");
                _LoginName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LoginName");
                OnLoginNameChanged();
            }
        }
        private global::System.String _LoginName;
        partial void OnLoginNameChanging(global::System.String value);
        partial void OnLoginNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmailAddress
        {
            get
            {
                return _EmailAddress;
            }
            set
            {
                OnEmailAddressChanging(value);
                ReportPropertyChanging("EmailAddress");
                _EmailAddress = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmailAddress");
                OnEmailAddressChanged();
            }
        }
        private global::System.String _EmailAddress;
        partial void OnEmailAddressChanging(global::System.String value);
        partial void OnEmailAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastLogin
        {
            get
            {
                return _LastLogin;
            }
            set
            {
                OnLastLoginChanging(value);
                ReportPropertyChanging("LastLogin");
                _LastLogin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastLogin");
                OnLastLoginChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastLogin;
        partial void OnLastLoginChanging(Nullable<global::System.DateTime> value);
        partial void OnLastLoginChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AgileMindModel", "FK_t_GameResults_Logins", "t_GameResults")]
        public EntityCollection<t_GameResults> t_GameResults
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<t_GameResults>("AgileMindModel.FK_t_GameResults_Logins", "t_GameResults");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<t_GameResults>("AgileMindModel.FK_t_GameResults_Logins", "t_GameResults", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AgileMindModel", "FK_t_UserProfileAnswer_Logins", "t_UserProfileAnswer")]
        public EntityCollection<t_UserProfileAnswer> t_UserProfileAnswer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<t_UserProfileAnswer>("AgileMindModel.FK_t_UserProfileAnswer_Logins", "t_UserProfileAnswer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<t_UserProfileAnswer>("AgileMindModel.FK_t_UserProfileAnswer_Logins", "t_UserProfileAnswer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AgileMindModel", "FK_t_LoginSession_Logins", "t_LoginSession")]
        public EntityCollection<t_LoginSession> t_LoginSession
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<t_LoginSession>("AgileMindModel.FK_t_LoginSession_Logins", "t_LoginSession");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<t_LoginSession>("AgileMindModel.FK_t_LoginSession_Logins", "t_LoginSession", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AgileMindModel", Name="t_Game")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_Game : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new t_Game object.
        /// </summary>
        /// <param name="gameId">Initial value of the GameId property.</param>
        /// <param name="game">Initial value of the Game property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static t_Game Createt_Game(global::System.Int32 gameId, global::System.String game, global::System.String description)
        {
            t_Game t_Game = new t_Game();
            t_Game.GameId = gameId;
            t_Game.Game = game;
            t_Game.Description = description;
            return t_Game;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GameId
        {
            get
            {
                return _GameId;
            }
            set
            {
                if (_GameId != value)
                {
                    OnGameIdChanging(value);
                    ReportPropertyChanging("GameId");
                    _GameId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GameId");
                    OnGameIdChanged();
                }
            }
        }
        private global::System.Int32 _GameId;
        partial void OnGameIdChanging(global::System.Int32 value);
        partial void OnGameIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Game
        {
            get
            {
                return _Game;
            }
            set
            {
                OnGameChanging(value);
                ReportPropertyChanging("Game");
                _Game = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Game");
                OnGameChanged();
            }
        }
        private global::System.String _Game;
        partial void OnGameChanging(global::System.String value);
        partial void OnGameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AgileMindModel", "FK_t_GameResults_t_Game", "t_GameResults")]
        public EntityCollection<t_GameResults> t_GameResults
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<t_GameResults>("AgileMindModel.FK_t_GameResults_t_Game", "t_GameResults");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<t_GameResults>("AgileMindModel.FK_t_GameResults_t_Game", "t_GameResults", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AgileMindModel", Name="t_GameResults")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_GameResults : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new t_GameResults object.
        /// </summary>
        /// <param name="gameScoreId">Initial value of the GameScoreId property.</param>
        /// <param name="gameId">Initial value of the GameId property.</param>
        /// <param name="loginId">Initial value of the LoginId property.</param>
        /// <param name="created">Initial value of the Created property.</param>
        /// <param name="score">Initial value of the Score property.</param>
        /// <param name="total">Initial value of the Total property.</param>
        public static t_GameResults Createt_GameResults(global::System.Int32 gameScoreId, global::System.Int32 gameId, global::System.Int32 loginId, global::System.DateTime created, global::System.Int32 score, global::System.Int32 total)
        {
            t_GameResults t_GameResults = new t_GameResults();
            t_GameResults.GameScoreId = gameScoreId;
            t_GameResults.GameId = gameId;
            t_GameResults.LoginId = loginId;
            t_GameResults.Created = created;
            t_GameResults.Score = score;
            t_GameResults.Total = total;
            return t_GameResults;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GameScoreId
        {
            get
            {
                return _GameScoreId;
            }
            set
            {
                if (_GameScoreId != value)
                {
                    OnGameScoreIdChanging(value);
                    ReportPropertyChanging("GameScoreId");
                    _GameScoreId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GameScoreId");
                    OnGameScoreIdChanged();
                }
            }
        }
        private global::System.Int32 _GameScoreId;
        partial void OnGameScoreIdChanging(global::System.Int32 value);
        partial void OnGameScoreIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GameId
        {
            get
            {
                return _GameId;
            }
            set
            {
                OnGameIdChanging(value);
                ReportPropertyChanging("GameId");
                _GameId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GameId");
                OnGameIdChanged();
            }
        }
        private global::System.Int32 _GameId;
        partial void OnGameIdChanging(global::System.Int32 value);
        partial void OnGameIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LoginId
        {
            get
            {
                return _LoginId;
            }
            set
            {
                OnLoginIdChanging(value);
                ReportPropertyChanging("LoginId");
                _LoginId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LoginId");
                OnLoginIdChanged();
            }
        }
        private global::System.Int32 _LoginId;
        partial void OnLoginIdChanging(global::System.Int32 value);
        partial void OnLoginIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Score
        {
            get
            {
                return _Score;
            }
            set
            {
                OnScoreChanging(value);
                ReportPropertyChanging("Score");
                _Score = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Score");
                OnScoreChanged();
            }
        }
        private global::System.Int32 _Score;
        partial void OnScoreChanging(global::System.Int32 value);
        partial void OnScoreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Total
        {
            get
            {
                return _Total;
            }
            set
            {
                OnTotalChanging(value);
                ReportPropertyChanging("Total");
                _Total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Total");
                OnTotalChanged();
            }
        }
        private global::System.Int32 _Total;
        partial void OnTotalChanging(global::System.Int32 value);
        partial void OnTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TestDuration
        {
            get
            {
                return _TestDuration;
            }
            set
            {
                OnTestDurationChanging(value);
                ReportPropertyChanging("TestDuration");
                _TestDuration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TestDuration");
                OnTestDurationChanged();
            }
        }
        private Nullable<global::System.Decimal> _TestDuration;
        partial void OnTestDurationChanging(Nullable<global::System.Decimal> value);
        partial void OnTestDurationChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AgileMindModel", "FK_t_GameResults_Logins", "Login")]
        public Login Login
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Login>("AgileMindModel.FK_t_GameResults_Logins", "Login").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Login>("AgileMindModel.FK_t_GameResults_Logins", "Login").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Login> LoginReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Login>("AgileMindModel.FK_t_GameResults_Logins", "Login");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Login>("AgileMindModel.FK_t_GameResults_Logins", "Login", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AgileMindModel", "FK_t_GameResults_t_Game", "t_Game")]
        public t_Game t_Game
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_Game>("AgileMindModel.FK_t_GameResults_t_Game", "t_Game").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_Game>("AgileMindModel.FK_t_GameResults_t_Game", "t_Game").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<t_Game> t_GameReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_Game>("AgileMindModel.FK_t_GameResults_t_Game", "t_Game");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<t_Game>("AgileMindModel.FK_t_GameResults_t_Game", "t_Game", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AgileMindModel", Name="t_LoginSession")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_LoginSession : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new t_LoginSession object.
        /// </summary>
        /// <param name="loginSessionId">Initial value of the LoginSessionId property.</param>
        /// <param name="loginId">Initial value of the LoginId property.</param>
        /// <param name="validTill">Initial value of the ValidTill property.</param>
        public static t_LoginSession Createt_LoginSession(global::System.Guid loginSessionId, global::System.Int32 loginId, global::System.DateTime validTill)
        {
            t_LoginSession t_LoginSession = new t_LoginSession();
            t_LoginSession.LoginSessionId = loginSessionId;
            t_LoginSession.LoginId = loginId;
            t_LoginSession.ValidTill = validTill;
            return t_LoginSession;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid LoginSessionId
        {
            get
            {
                return _LoginSessionId;
            }
            set
            {
                if (_LoginSessionId != value)
                {
                    OnLoginSessionIdChanging(value);
                    ReportPropertyChanging("LoginSessionId");
                    _LoginSessionId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LoginSessionId");
                    OnLoginSessionIdChanged();
                }
            }
        }
        private global::System.Guid _LoginSessionId;
        partial void OnLoginSessionIdChanging(global::System.Guid value);
        partial void OnLoginSessionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LoginId
        {
            get
            {
                return _LoginId;
            }
            set
            {
                OnLoginIdChanging(value);
                ReportPropertyChanging("LoginId");
                _LoginId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LoginId");
                OnLoginIdChanged();
            }
        }
        private global::System.Int32 _LoginId;
        partial void OnLoginIdChanging(global::System.Int32 value);
        partial void OnLoginIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ValidTill
        {
            get
            {
                return _ValidTill;
            }
            set
            {
                OnValidTillChanging(value);
                ReportPropertyChanging("ValidTill");
                _ValidTill = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ValidTill");
                OnValidTillChanged();
            }
        }
        private global::System.DateTime _ValidTill;
        partial void OnValidTillChanging(global::System.DateTime value);
        partial void OnValidTillChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AgileMindModel", "FK_t_LoginSession_Logins", "Login")]
        public Login Login
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Login>("AgileMindModel.FK_t_LoginSession_Logins", "Login").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Login>("AgileMindModel.FK_t_LoginSession_Logins", "Login").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Login> LoginReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Login>("AgileMindModel.FK_t_LoginSession_Logins", "Login");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Login>("AgileMindModel.FK_t_LoginSession_Logins", "Login", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AgileMindModel", Name="t_UserProfileAnswer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_UserProfileAnswer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new t_UserProfileAnswer object.
        /// </summary>
        /// <param name="userProfileAnswerId">Initial value of the UserProfileAnswerId property.</param>
        /// <param name="loginId">Initial value of the LoginId property.</param>
        /// <param name="userProfileQuestionId">Initial value of the UserProfileQuestionId property.</param>
        /// <param name="answer">Initial value of the Answer property.</param>
        /// <param name="created">Initial value of the Created property.</param>
        /// <param name="noAnswer">Initial value of the NoAnswer property.</param>
        public static t_UserProfileAnswer Createt_UserProfileAnswer(global::System.Int32 userProfileAnswerId, global::System.Int32 loginId, global::System.Int32 userProfileQuestionId, global::System.String answer, global::System.DateTime created, global::System.Boolean noAnswer)
        {
            t_UserProfileAnswer t_UserProfileAnswer = new t_UserProfileAnswer();
            t_UserProfileAnswer.UserProfileAnswerId = userProfileAnswerId;
            t_UserProfileAnswer.LoginId = loginId;
            t_UserProfileAnswer.UserProfileQuestionId = userProfileQuestionId;
            t_UserProfileAnswer.Answer = answer;
            t_UserProfileAnswer.Created = created;
            t_UserProfileAnswer.NoAnswer = noAnswer;
            return t_UserProfileAnswer;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserProfileAnswerId
        {
            get
            {
                return _UserProfileAnswerId;
            }
            set
            {
                if (_UserProfileAnswerId != value)
                {
                    OnUserProfileAnswerIdChanging(value);
                    ReportPropertyChanging("UserProfileAnswerId");
                    _UserProfileAnswerId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserProfileAnswerId");
                    OnUserProfileAnswerIdChanged();
                }
            }
        }
        private global::System.Int32 _UserProfileAnswerId;
        partial void OnUserProfileAnswerIdChanging(global::System.Int32 value);
        partial void OnUserProfileAnswerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LoginId
        {
            get
            {
                return _LoginId;
            }
            set
            {
                OnLoginIdChanging(value);
                ReportPropertyChanging("LoginId");
                _LoginId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LoginId");
                OnLoginIdChanged();
            }
        }
        private global::System.Int32 _LoginId;
        partial void OnLoginIdChanging(global::System.Int32 value);
        partial void OnLoginIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserProfileQuestionId
        {
            get
            {
                return _UserProfileQuestionId;
            }
            set
            {
                OnUserProfileQuestionIdChanging(value);
                ReportPropertyChanging("UserProfileQuestionId");
                _UserProfileQuestionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserProfileQuestionId");
                OnUserProfileQuestionIdChanged();
            }
        }
        private global::System.Int32 _UserProfileQuestionId;
        partial void OnUserProfileQuestionIdChanging(global::System.Int32 value);
        partial void OnUserProfileQuestionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Answer
        {
            get
            {
                return _Answer;
            }
            set
            {
                OnAnswerChanging(value);
                ReportPropertyChanging("Answer");
                _Answer = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Answer");
                OnAnswerChanged();
            }
        }
        private global::System.String _Answer;
        partial void OnAnswerChanging(global::System.String value);
        partial void OnAnswerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean NoAnswer
        {
            get
            {
                return _NoAnswer;
            }
            set
            {
                OnNoAnswerChanging(value);
                ReportPropertyChanging("NoAnswer");
                _NoAnswer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NoAnswer");
                OnNoAnswerChanged();
            }
        }
        private global::System.Boolean _NoAnswer;
        partial void OnNoAnswerChanging(global::System.Boolean value);
        partial void OnNoAnswerChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AgileMindModel", "FK_t_UserProfileAnswer_Logins", "Login")]
        public Login Login
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Login>("AgileMindModel.FK_t_UserProfileAnswer_Logins", "Login").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Login>("AgileMindModel.FK_t_UserProfileAnswer_Logins", "Login").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Login> LoginReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Login>("AgileMindModel.FK_t_UserProfileAnswer_Logins", "Login");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Login>("AgileMindModel.FK_t_UserProfileAnswer_Logins", "Login", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AgileMindModel", "FK_t_UserProfileAnswer_t_UserProfileQuestion", "t_UserProfileQuestion")]
        public t_UserProfileQuestion t_UserProfileQuestion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_UserProfileQuestion>("AgileMindModel.FK_t_UserProfileAnswer_t_UserProfileQuestion", "t_UserProfileQuestion").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_UserProfileQuestion>("AgileMindModel.FK_t_UserProfileAnswer_t_UserProfileQuestion", "t_UserProfileQuestion").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<t_UserProfileQuestion> t_UserProfileQuestionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_UserProfileQuestion>("AgileMindModel.FK_t_UserProfileAnswer_t_UserProfileQuestion", "t_UserProfileQuestion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<t_UserProfileQuestion>("AgileMindModel.FK_t_UserProfileAnswer_t_UserProfileQuestion", "t_UserProfileQuestion", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AgileMindModel", Name="t_UserProfileQuestion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_UserProfileQuestion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new t_UserProfileQuestion object.
        /// </summary>
        /// <param name="userProfileQuestionId">Initial value of the UserProfileQuestionId property.</param>
        /// <param name="question">Initial value of the Question property.</param>
        /// <param name="order">Initial value of the Order property.</param>
        /// <param name="created">Initial value of the Created property.</param>
        /// <param name="active">Initial value of the Active property.</param>
        public static t_UserProfileQuestion Createt_UserProfileQuestion(global::System.Int32 userProfileQuestionId, global::System.String question, global::System.Byte order, global::System.DateTime created, global::System.Boolean active)
        {
            t_UserProfileQuestion t_UserProfileQuestion = new t_UserProfileQuestion();
            t_UserProfileQuestion.UserProfileQuestionId = userProfileQuestionId;
            t_UserProfileQuestion.Question = question;
            t_UserProfileQuestion.Order = order;
            t_UserProfileQuestion.Created = created;
            t_UserProfileQuestion.Active = active;
            return t_UserProfileQuestion;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserProfileQuestionId
        {
            get
            {
                return _UserProfileQuestionId;
            }
            set
            {
                if (_UserProfileQuestionId != value)
                {
                    OnUserProfileQuestionIdChanging(value);
                    ReportPropertyChanging("UserProfileQuestionId");
                    _UserProfileQuestionId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserProfileQuestionId");
                    OnUserProfileQuestionIdChanged();
                }
            }
        }
        private global::System.Int32 _UserProfileQuestionId;
        partial void OnUserProfileQuestionIdChanging(global::System.Int32 value);
        partial void OnUserProfileQuestionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Question
        {
            get
            {
                return _Question;
            }
            set
            {
                OnQuestionChanging(value);
                ReportPropertyChanging("Question");
                _Question = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Question");
                OnQuestionChanged();
            }
        }
        private global::System.String _Question;
        partial void OnQuestionChanging(global::System.String value);
        partial void OnQuestionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Order
        {
            get
            {
                return _Order;
            }
            set
            {
                OnOrderChanging(value);
                ReportPropertyChanging("Order");
                _Order = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Order");
                OnOrderChanged();
            }
        }
        private global::System.Byte _Order;
        partial void OnOrderChanging(global::System.Byte value);
        partial void OnOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AgileMindModel", "FK_t_UserProfileAnswer_t_UserProfileQuestion", "t_UserProfileAnswer")]
        public EntityCollection<t_UserProfileAnswer> t_UserProfileAnswer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<t_UserProfileAnswer>("AgileMindModel.FK_t_UserProfileAnswer_t_UserProfileQuestion", "t_UserProfileAnswer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<t_UserProfileAnswer>("AgileMindModel.FK_t_UserProfileAnswer_t_UserProfileQuestion", "t_UserProfileAnswer", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AgileMindModel", Name="vwLoginInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwLoginInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vwLoginInfo object.
        /// </summary>
        /// <param name="loginId">Initial value of the LoginId property.</param>
        /// <param name="loginName">Initial value of the LoginName property.</param>
        /// <param name="emailAddress">Initial value of the EmailAddress property.</param>
        /// <param name="active">Initial value of the Active property.</param>
        /// <param name="created">Initial value of the Created property.</param>
        public static vwLoginInfo CreatevwLoginInfo(global::System.Int32 loginId, global::System.String loginName, global::System.String emailAddress, global::System.Boolean active, global::System.DateTime created)
        {
            vwLoginInfo vwLoginInfo = new vwLoginInfo();
            vwLoginInfo.LoginId = loginId;
            vwLoginInfo.LoginName = loginName;
            vwLoginInfo.EmailAddress = emailAddress;
            vwLoginInfo.Active = active;
            vwLoginInfo.Created = created;
            return vwLoginInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LoginId
        {
            get
            {
                return _LoginId;
            }
            set
            {
                if (_LoginId != value)
                {
                    OnLoginIdChanging(value);
                    ReportPropertyChanging("LoginId");
                    _LoginId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LoginId");
                    OnLoginIdChanged();
                }
            }
        }
        private global::System.Int32 _LoginId;
        partial void OnLoginIdChanging(global::System.Int32 value);
        partial void OnLoginIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LoginName
        {
            get
            {
                return _LoginName;
            }
            set
            {
                if (_LoginName != value)
                {
                    OnLoginNameChanging(value);
                    ReportPropertyChanging("LoginName");
                    _LoginName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("LoginName");
                    OnLoginNameChanged();
                }
            }
        }
        private global::System.String _LoginName;
        partial void OnLoginNameChanging(global::System.String value);
        partial void OnLoginNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmailAddress
        {
            get
            {
                return _EmailAddress;
            }
            set
            {
                if (_EmailAddress != value)
                {
                    OnEmailAddressChanging(value);
                    ReportPropertyChanging("EmailAddress");
                    _EmailAddress = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("EmailAddress");
                    OnEmailAddressChanged();
                }
            }
        }
        private global::System.String _EmailAddress;
        partial void OnEmailAddressChanging(global::System.String value);
        partial void OnEmailAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                if (_Active != value)
                {
                    OnActiveChanging(value);
                    ReportPropertyChanging("Active");
                    _Active = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Active");
                    OnActiveChanged();
                }
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Created
        {
            get
            {
                return _Created;
            }
            set
            {
                if (_Created != value)
                {
                    OnCreatedChanging(value);
                    ReportPropertyChanging("Created");
                    _Created = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Created");
                    OnCreatedChanged();
                }
            }
        }
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastLogin
        {
            get
            {
                return _LastLogin;
            }
            set
            {
                OnLastLoginChanging(value);
                ReportPropertyChanging("LastLogin");
                _LastLogin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastLogin");
                OnLastLoginChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastLogin;
        partial void OnLastLoginChanging(Nullable<global::System.DateTime> value);
        partial void OnLastLoginChanged();

        #endregion

    
    }

    #endregion

    
}
