//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace AgileMind.DAL.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AgileMindEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AgileMindEntities object using the connection string found in the 'AgileMindEntities' section of the application configuration file.
        /// </summary>
        public AgileMindEntities() : base("name=AgileMindEntities", "AgileMindEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AgileMindEntities object.
        /// </summary>
        public AgileMindEntities(string connectionString) : base(connectionString, "AgileMindEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AgileMindEntities object.
        /// </summary>
        public AgileMindEntities(EntityConnection connection) : base(connection, "AgileMindEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Login> Logins
        {
            get
            {
                if ((_Logins == null))
                {
                    _Logins = base.CreateObjectSet<Login>("Logins");
                }
                return _Logins;
            }
        }
        private ObjectSet<Login> _Logins;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vwLoginInfo> vwLoginInfoes
        {
            get
            {
                if ((_vwLoginInfoes == null))
                {
                    _vwLoginInfoes = base.CreateObjectSet<vwLoginInfo>("vwLoginInfoes");
                }
                return _vwLoginInfoes;
            }
        }
        private ObjectSet<vwLoginInfo> _vwLoginInfoes;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Logins EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLogins(Login login)
        {
            base.AddObject("Logins", login);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vwLoginInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovwLoginInfoes(vwLoginInfo vwLoginInfo)
        {
            base.AddObject("vwLoginInfoes", vwLoginInfo);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="loginName">No Metadata Documentation available.</param>
        /// <param name="password">No Metadata Documentation available.</param>
        public ObjectResult<Login> Logins_CheckLogin(global::System.String loginName, global::System.String password)
        {
            ObjectParameter loginNameParameter;
            if (loginName != null)
            {
                loginNameParameter = new ObjectParameter("LoginName", loginName);
            }
            else
            {
                loginNameParameter = new ObjectParameter("LoginName", typeof(global::System.String));
            }
    
            ObjectParameter passwordParameter;
            if (password != null)
            {
                passwordParameter = new ObjectParameter("Password", password);
            }
            else
            {
                passwordParameter = new ObjectParameter("Password", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<Login>("Logins_CheckLogin", loginNameParameter, passwordParameter);
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        /// <param name="loginName">No Metadata Documentation available.</param>
        /// <param name="password">No Metadata Documentation available.</param>
        public ObjectResult<Login> Logins_CheckLogin(global::System.String loginName, global::System.String password, MergeOption mergeOption)
        {
            ObjectParameter loginNameParameter;
            if (loginName != null)
            {
                loginNameParameter = new ObjectParameter("LoginName", loginName);
            }
            else
            {
                loginNameParameter = new ObjectParameter("LoginName", typeof(global::System.String));
            }
    
            ObjectParameter passwordParameter;
            if (password != null)
            {
                passwordParameter = new ObjectParameter("Password", password);
            }
            else
            {
                passwordParameter = new ObjectParameter("Password", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<Login>("Logins_CheckLogin", mergeOption, loginNameParameter, passwordParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="loginId">No Metadata Documentation available.</param>
        public ObjectResult<vwLoginInfo> vw_LoginInfo_FetchByLoginId(Nullable<global::System.Int32> loginId)
        {
            ObjectParameter loginIdParameter;
            if (loginId.HasValue)
            {
                loginIdParameter = new ObjectParameter("LoginId", loginId);
            }
            else
            {
                loginIdParameter = new ObjectParameter("LoginId", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<vwLoginInfo>("vw_LoginInfo_FetchByLoginId", loginIdParameter);
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        /// <param name="loginId">No Metadata Documentation available.</param>
        public ObjectResult<vwLoginInfo> vw_LoginInfo_FetchByLoginId(Nullable<global::System.Int32> loginId, MergeOption mergeOption)
        {
            ObjectParameter loginIdParameter;
            if (loginId.HasValue)
            {
                loginIdParameter = new ObjectParameter("LoginId", loginId);
            }
            else
            {
                loginIdParameter = new ObjectParameter("LoginId", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<vwLoginInfo>("vw_LoginInfo_FetchByLoginId", mergeOption, loginIdParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AgileMindModel", Name="Login")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Login : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Login object.
        /// </summary>
        /// <param name="loginId">Initial value of the LoginId property.</param>
        /// <param name="loginName">Initial value of the LoginName property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="emailAddress">Initial value of the EmailAddress property.</param>
        /// <param name="active">Initial value of the Active property.</param>
        /// <param name="created">Initial value of the Created property.</param>
        public static Login CreateLogin(global::System.Int32 loginId, global::System.String loginName, global::System.String password, global::System.String emailAddress, global::System.Boolean active, global::System.DateTime created)
        {
            Login login = new Login();
            login.LoginId = loginId;
            login.LoginName = loginName;
            login.Password = password;
            login.EmailAddress = emailAddress;
            login.Active = active;
            login.Created = created;
            return login;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LoginId
        {
            get
            {
                return _LoginId;
            }
            set
            {
                if (_LoginId != value)
                {
                    OnLoginIdChanging(value);
                    ReportPropertyChanging("LoginId");
                    _LoginId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LoginId");
                    OnLoginIdChanged();
                }
            }
        }
        private global::System.Int32 _LoginId;
        partial void OnLoginIdChanging(global::System.Int32 value);
        partial void OnLoginIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LoginName
        {
            get
            {
                return _LoginName;
            }
            set
            {
                OnLoginNameChanging(value);
                ReportPropertyChanging("LoginName");
                _LoginName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LoginName");
                OnLoginNameChanged();
            }
        }
        private global::System.String _LoginName;
        partial void OnLoginNameChanging(global::System.String value);
        partial void OnLoginNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmailAddress
        {
            get
            {
                return _EmailAddress;
            }
            set
            {
                OnEmailAddressChanging(value);
                ReportPropertyChanging("EmailAddress");
                _EmailAddress = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmailAddress");
                OnEmailAddressChanged();
            }
        }
        private global::System.String _EmailAddress;
        partial void OnEmailAddressChanging(global::System.String value);
        partial void OnEmailAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastLogin
        {
            get
            {
                return _LastLogin;
            }
            set
            {
                OnLastLoginChanging(value);
                ReportPropertyChanging("LastLogin");
                _LastLogin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastLogin");
                OnLastLoginChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastLogin;
        partial void OnLastLoginChanging(Nullable<global::System.DateTime> value);
        partial void OnLastLoginChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AgileMindModel", Name="vwLoginInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwLoginInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vwLoginInfo object.
        /// </summary>
        /// <param name="loginId">Initial value of the LoginId property.</param>
        /// <param name="loginName">Initial value of the LoginName property.</param>
        /// <param name="emailAddress">Initial value of the EmailAddress property.</param>
        /// <param name="active">Initial value of the Active property.</param>
        /// <param name="created">Initial value of the Created property.</param>
        public static vwLoginInfo CreatevwLoginInfo(global::System.Int32 loginId, global::System.String loginName, global::System.String emailAddress, global::System.Boolean active, global::System.DateTime created)
        {
            vwLoginInfo vwLoginInfo = new vwLoginInfo();
            vwLoginInfo.LoginId = loginId;
            vwLoginInfo.LoginName = loginName;
            vwLoginInfo.EmailAddress = emailAddress;
            vwLoginInfo.Active = active;
            vwLoginInfo.Created = created;
            return vwLoginInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LoginId
        {
            get
            {
                return _LoginId;
            }
            set
            {
                if (_LoginId != value)
                {
                    OnLoginIdChanging(value);
                    ReportPropertyChanging("LoginId");
                    _LoginId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LoginId");
                    OnLoginIdChanged();
                }
            }
        }
        private global::System.Int32 _LoginId;
        partial void OnLoginIdChanging(global::System.Int32 value);
        partial void OnLoginIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LoginName
        {
            get
            {
                return _LoginName;
            }
            set
            {
                if (_LoginName != value)
                {
                    OnLoginNameChanging(value);
                    ReportPropertyChanging("LoginName");
                    _LoginName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("LoginName");
                    OnLoginNameChanged();
                }
            }
        }
        private global::System.String _LoginName;
        partial void OnLoginNameChanging(global::System.String value);
        partial void OnLoginNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmailAddress
        {
            get
            {
                return _EmailAddress;
            }
            set
            {
                if (_EmailAddress != value)
                {
                    OnEmailAddressChanging(value);
                    ReportPropertyChanging("EmailAddress");
                    _EmailAddress = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("EmailAddress");
                    OnEmailAddressChanged();
                }
            }
        }
        private global::System.String _EmailAddress;
        partial void OnEmailAddressChanging(global::System.String value);
        partial void OnEmailAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                if (_Active != value)
                {
                    OnActiveChanging(value);
                    ReportPropertyChanging("Active");
                    _Active = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Active");
                    OnActiveChanged();
                }
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Created
        {
            get
            {
                return _Created;
            }
            set
            {
                if (_Created != value)
                {
                    OnCreatedChanging(value);
                    ReportPropertyChanging("Created");
                    _Created = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Created");
                    OnCreatedChanged();
                }
            }
        }
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastLogin
        {
            get
            {
                return _LastLogin;
            }
            set
            {
                OnLastLoginChanging(value);
                ReportPropertyChanging("LastLogin");
                _LastLogin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastLogin");
                OnLastLoginChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastLogin;
        partial void OnLastLoginChanging(Nullable<global::System.DateTime> value);
        partial void OnLastLoginChanged();

        #endregion

    
    }

    #endregion

    
}
